/**
 * Generates docs/.vitepress/sidebar.ts from the filesystem.
 *
 * Conventions:
 *  - A directory `foo/` is grouped under one collapsible item.
 *  - Its "index" page is either `foo/index.md` or sibling `foo.md`.
 *  - Each .md file's display text is its first level-1 heading; falls back to
 *    a humanised filename.
 *  - Inside a group, leaf pages come first (alphabetical), then nested groups
 *    (alphabetical). This keeps overview/utility pages above deep dives.
 *
 * Run with: pnpm migrate:sidebar
 */

import * as fs from "node:fs";
import * as path from "node:path";

const ROOT = process.cwd();
const DOCS = path.join(ROOT, "docs");
const OUT = path.join(DOCS, ".vitepress", "sidebar.ts");

// Top-level sections that get their own keyed sidebar. The wrapper text is
// the H1 of `<section>/index.md`.
const SECTIONS = ["printers", "parts", "firmware", "electronics"];

type SidebarItem = {
  text: string;
  link?: string;
  collapsed?: boolean;
  items?: SidebarItem[];
};

function extractH1(absFile: string): string | null {
  const raw = fs.readFileSync(absFile, "utf8");
  // Strip frontmatter if present
  const body = raw.replace(/^---\n[\s\S]*?\n---\n/, "");
  const m = body.match(/^#\s+(.+?)\s*$/m);
  return m ? m[1].trim() : null;
}

function humanize(slug: string): string {
  return slug
    .replace(/[-_]+/g, " ")
    .replace(/\.md$/, "")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function buildSection(dirAbs: string, urlPrefix: string): SidebarItem[] {
  const leafItems: SidebarItem[] = [];
  const groupItems: SidebarItem[] = [];

  const entries = fs.readdirSync(dirAbs, { withFileTypes: true });
  const files = entries.filter((e) => e.isFile() && e.name.endsWith(".md"));
  const dirs = entries.filter((e) => e.isDirectory());
  const dirNames = new Set(dirs.map((d) => d.name));

  // 1. Plain leaf .md files (no sibling directory consuming them as index).
  for (const f of files) {
    const base = f.name.slice(0, -3);
    if (base === "index") continue;
    if (dirNames.has(base)) continue; // serves as index for that directory
    const filePath = path.join(dirAbs, f.name);
    leafItems.push({
      text: extractH1(filePath) ?? humanize(base),
      link: `${urlPrefix}/${base}`,
    });
  }

  // 2. Directories become collapsible groups.
  for (const d of dirs) {
    const subAbs = path.join(dirAbs, d.name);
    const subUrl = `${urlPrefix}/${d.name}`;

    const indexInside = path.join(subAbs, "index.md");
    const indexSibling = path.join(dirAbs, `${d.name}.md`);
    let indexFile: string | null = null;
    if (fs.existsSync(indexInside)) indexFile = indexInside;
    else if (fs.existsSync(indexSibling)) indexFile = indexSibling;

    const title = indexFile
      ? (extractH1(indexFile) ?? humanize(d.name))
      : humanize(d.name);
    const children = buildSection(subAbs, subUrl);

    const group: SidebarItem = { text: title, collapsed: true };
    if (indexFile) group.link = subUrl;
    if (children.length > 0) group.items = children;
    groupItems.push(group);
  }

  leafItems.sort((a, b) => a.text.localeCompare(b.text));
  groupItems.sort((a, b) => a.text.localeCompare(b.text));
  return [...leafItems, ...groupItems];
}

function buildAll(): Record<string, SidebarItem[]> {
  const sidebar: Record<string, SidebarItem[]> = {};
  for (const section of SECTIONS) {
    const dirAbs = path.join(DOCS, section);
    if (!fs.existsSync(dirAbs)) continue;
    const indexFile = path.join(dirAbs, "index.md");
    const title = fs.existsSync(indexFile)
      ? (extractH1(indexFile) ?? humanize(section))
      : humanize(section);
    const items = buildSection(dirAbs, `/${section}`);
    sidebar[`/${section}/`] = [
      { text: title, link: `/${section}/`, items },
    ];
  }
  return sidebar;
}

// Pretty-print a SidebarItem tree as TypeScript source. We hand-roll this so
// the generated file is diff-friendly and stable across runs.
function serialize(value: unknown, indent = 0): string {
  const pad = "  ".repeat(indent);
  const padInner = "  ".repeat(indent + 1);
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const parts = value.map((v) => `${padInner}${serialize(v, indent + 1)}`);
    return `[\n${parts.join(",\n")},\n${pad}]`;
  }
  if (value && typeof value === "object") {
    const obj = value as Record<string, unknown>;
    const keys = Object.keys(obj);
    if (keys.length === 0) return "{}";
    const parts = keys.map((k) => {
      const v = obj[k];
      const key = /^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k);
      return `${padInner}${key}: ${serialize(v, indent + 1)}`;
    });
    return `{\n${parts.join(",\n")},\n${pad}}`;
  }
  return JSON.stringify(value);
}

function main() {
  const sidebar = buildAll();
  const banner = `// AUTO-GENERATED by migration/generate-sidebar.ts. Do not edit by hand.\n// Run \`pnpm migrate:sidebar\` to regenerate after content changes.\n\nimport type { DefaultTheme } from 'vitepress'\n\nexport const sidebar: DefaultTheme.Sidebar = `;
  const body = serialize(sidebar) + "\n";
  fs.writeFileSync(OUT, banner + body, "utf8");

  // Quick summary
  let pageCount = 0;
  const walk = (items: SidebarItem[]) => {
    for (const it of items) {
      if (it.link) pageCount++;
      if (it.items) walk(it.items);
    }
  };
  for (const arr of Object.values(sidebar)) walk(arr);
  console.log(`Wrote ${path.relative(ROOT, OUT)}`);
  console.log(`  sections : ${Object.keys(sidebar).length}`);
  console.log(`  links    : ${pageCount}`);
}

main();
