import { defineConfig } from 'vitepress'
import { sidebar } from './sidebar'

// Sidebar/nav are intentionally kept small here, most sections are
// generated by docs/.vitepress/sidebar.ts from the filesystem. This file
// only declares site-wide settings and top-nav.

export default defineConfig({
  title: '3DPrint.Wiki',
  description: 'Community-curated knowledge base for 3D printing: printers, firmware, mods, and references.',
  lang: 'en-US',
  cleanUrls: true,
  lastUpdated: true,
  // VitePress otherwise tries to resolve links to non-page static assets like
  // `.zip` / `.xlsx` / `.pdf` files under `/images/` as routable pages and
  // flags them as dead. They are served by Vite as static assets from
  // `docs/public/` and resolve correctly in the browser.
  ignoreDeadLinks: [/^\/images\/.*\.(zip|pdf|xlsx?|docx?|csv|stl|gcode|7z|rar|tar\.gz)$/i],

  head: [
    ['link', { rel: 'icon', type: 'image/png', href: '/icon.png' }],
    ['meta', { name: 'theme-color', content: '#1f6feb' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:site_name', content: '3DPrint.Wiki' }],
    ['meta', { property: 'og:url', content: 'https://3dprint.wiki/' }],
  ],

  sitemap: {
    hostname: 'https://3dprint.wiki',
  },

  themeConfig: {
    logo: '/icon.png',
    siteTitle: '3DPrint.Wiki',

    nav: [
      { text: 'Home', link: '/' },
      { text: 'Printers', link: '/printers/' },
      { text: 'Parts', link: '/parts/' },
      { text: 'Firmware', link: '/firmware/' },
      { text: 'Electronics', link: '/electronics/' },
    ],

    // Sidebar is generated programmatically; see ./sidebar.ts.
    // Regenerate with `pnpm migrate:sidebar` after content changes.
    sidebar,

    socialLinks: [
      { icon: 'github', link: 'https://github.com/vidschofelix/3dprintwikipage' },
    ],

    editLink: {
      pattern: 'https://github.com/vidschofelix/3dprintwikipage/edit/main/docs/:path',
      text: 'Edit this page on GitHub',
    },

    search: {
      provider: 'local',
    },

    footer: {
      message: 'Community-maintained. Use at your own risk; see <a href="/disclaimer">disclaimer</a>.',
      copyright: 'Released into the wild under <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>.',
    },

    outline: [2, 3],
  },
})
