// AUTO-GENERATED by migration/generate-sidebar.ts. Do not edit by hand.
// Run `pnpm migrate:sidebar` to regenerate after content changes.

import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.Sidebar = {
  "/printers/": [
    {
      text: "Printers",
      link: "/printers/",
      items: [
        {
          text: "Anet",
          collapsed: true,
          items: [
            {
              text: "Anet A4",
              link: "/printers/anet/a4",
            },
            {
              text: "Anet A6",
              link: "/printers/anet/a6",
            },
            {
              text: "Anet A8 Plus",
              link: "/printers/anet/a8plus",
            },
            {
              text: "Anet E10",
              link: "/printers/anet/e10",
            },
            {
              text: "Anet A8",
              collapsed: true,
              link: "/printers/anet/a8",
              items: [
                {
                  text: "Anet Mainboard(s)",
                  link: "/printers/anet/a8/mainboard",
                },
                {
                  text: "Correct H-Carriage mount",
                  link: "/printers/anet/a8/bed-carriage",
                },
                {
                  text: "How to Change a Nozzle",
                  link: "/printers/anet/a8/nozzle",
                },
                {
                  text: "How to install the z-couplers (the right way)",
                  link: "/printers/anet/a8/coupler",
                },
                {
                  text: "Howto: Replace the Connectors on the Mainboard",
                  link: "/printers/anet/a8/replace_connectors",
                },
                {
                  text: "Locknuts",
                  link: "/printers/anet/a8/locknuts",
                },
                {
                  text: "Optimal Layer Heights",
                  link: "/printers/anet/a8/layer-heights",
                },
                {
                  text: "Replacing the hotbed connector",
                  link: "/printers/anet/a8/replace_hb_connector",
                },
                {
                  text: "Specification",
                  link: "/printers/anet/a8/specification",
                },
                {
                  text: "Stepper Motor",
                  link: "/printers/anet/a8/steppermotor",
                },
                {
                  text: "Belts",
                  collapsed: true,
                  items: [
                    {
                      text: "Howto",
                      collapsed: true,
                      items: [
                        {
                          text: "Choose and control belts",
                          link: "/printers/anet/a8/belts/howto/choose_and_control_belts",
                        },
                      ],
                    },
                  ],
                },
                {
                  text: "Improvements",
                  collapsed: true,
                  items: [
                    {
                      text: "Autolevel for the A8 Anet 3D Printer",
                      link: "/printers/anet/a8/improvements/autobedleveling",
                    },
                    {
                      text: "Heat bed insulation",
                      link: "/printers/anet/a8/improvements/heatbedinsulation",
                    },
                    {
                      text: "Howto: Thumbwheel Leveling",
                      link: "/printers/anet/a8/improvements/thumbwheelleveling",
                    },
                    {
                      text: "Understanding the heat bed",
                      link: "/printers/anet/a8/improvements/understanding_my_heatbed",
                    },
                  ],
                },
                {
                  text: "Slicer",
                  collapsed: true,
                  items: [
                    {
                      text: "Cura",
                      link: "/printers/anet/a8/slicer/cura",
                    },
                  ],
                },
              ],
            },
            {
              text: "Anet ET4",
              collapsed: true,
              link: "/printers/anet/et4",
              items: [
                {
                  text: "HowTo Setup and Flash Klipper on Anet ET4/Pro/X",
                  link: "/printers/anet/et4/setup-and-flash-klipper",
                },
              ],
            },
          ],
        },
        {
          text: "Bambu Lab",
          collapsed: true,
          items: [
            {
              text: "Bambu Lab P1P",
              link: "/printers/bambu-lab/p1p",
            },
          ],
        },
        {
          text: "Creality",
          collapsed: true,
          items: [
            {
              text: "Creality CR-10",
              link: "/printers/creality/cr-10",
            },
            {
              text: "Creality CR-6 SE/MAX",
              link: "/printers/creality/cr-6",
            },
            {
              text: "Creality Ender-3 S1",
              link: "/printers/creality/ender-3s1",
            },
            {
              text: "Ender-3",
              link: "/printers/creality/ender-3",
            },
          ],
        },
        {
          text: "Elegoo",
          collapsed: true,
          items: [
            {
              text: "Elegoo Mars",
              link: "/printers/elegoo/mars",
            },
          ],
        },
        {
          text: "Frames",
          collapsed: true,
          items: [
            {
              text: "P3Steel",
              link: "/printers/frames/p3steel",
            },
          ],
        },
        {
          text: "Geeetech",
          collapsed: true,
          items: [
            {
              text: "Geeetech i3",
              link: "/printers/geeetech/i3",
            },
          ],
        },
        {
          text: "Opensource",
          collapsed: true,
          items: [
            {
              text: "Corexy",
              collapsed: true,
              items: [
                {
                  text: "Hypercube",
                  link: "/printers/opensource/corexy/hypercube",
                },
              ],
            },
          ],
        },
        {
          text: "Tronxy",
          collapsed: true,
          items: [
            {
              text: "Tronxy X5S",
              link: "/printers/tronxy/x5s",
            },
          ],
        },
        {
          text: "Wanhao",
          collapsed: true,
          items: [
            {
              text: "Wanhao Duplicator 6+",
              link: "/printers/wanhao/duplicator6plus",
            },
            {
              text: "Wanhao Duplicator 6",
              collapsed: true,
              link: "/printers/wanhao/duplicator6",
              items: [
                {
                  text: "Convert To An Ultimaker 2 Hot End",
                  link: "/printers/wanhao/duplicator6/convert_to_an_ultimaker_2_hot_end",
                },
                {
                  text: "Featured Project Pages",
                  link: "/printers/wanhao/duplicator6/project_pages",
                },
                {
                  text: "Fire Hazard!",
                  link: "/printers/wanhao/duplicator6/fire_hazard",
                },
                {
                  text: "Firmware",
                  link: "/printers/wanhao/duplicator6/firmware",
                },
                {
                  text: "Printable Upgrades",
                  link: "/printers/wanhao/duplicator6/printable_upgrades",
                },
                {
                  text: "Purchasable Upgrade Parts",
                  link: "/printers/wanhao/duplicator6/purchaseable_upgrade_parts",
                },
                {
                  text: "Replacement Fans",
                  link: "/printers/wanhao/duplicator6/replacement_fans",
                },
                {
                  text: "Specifications",
                  link: "/printers/wanhao/duplicator6/specifications",
                },
                {
                  text: "Stock Unit Parts List",
                  link: "/printers/wanhao/duplicator6/stock_parts_list",
                },
                {
                  text: "Troubleshooting",
                  link: "/printers/wanhao/duplicator6/troubleshooting",
                },
                {
                  text: "Upgrade Parts List",
                  link: "/printers/wanhao/duplicator6/upgrade_parts_list",
                },
                {
                  text: "Useful Equipment and Supplies",
                  link: "/printers/wanhao/duplicator6/useful_equipment_and_supplies",
                },
                {
                  text: "How To Guides",
                  collapsed: true,
                  link: "/printers/wanhao/duplicator6/how-to_guides",
                  items: [
                    {
                      text: "How to flash this firmware",
                      link: "/printers/wanhao/duplicator6/how-to_guides/flash_firmware_.hex_file",
                    },
                    {
                      text: "How to Properly Tighten the Nozzle+Heat Block+Heat Tube Assembly",
                      link: "/printers/wanhao/duplicator6/how-to_guides/properly_tighten_nozzle_heat_block_heat_tube_assembly",
                    },
                    {
                      text: "Upgrading to Z-probe Sensor",
                      link: "/printers/wanhao/duplicator6/how-to_guides/z-probe_upgrade",
                    },
                  ],
                },
                {
                  text: "Major Components",
                  collapsed: true,
                  link: "/printers/wanhao/duplicator6/major_components",
                  items: [
                    {
                      text: "ATMEGA 2560-16AU",
                      link: "/printers/wanhao/duplicator6/major_components/cpu",
                    },
                    {
                      text: "Control Board",
                      link: "/printers/wanhao/duplicator6/major_components/control_board",
                    },
                    {
                      text: "Extruder",
                      link: "/printers/wanhao/duplicator6/major_components/extruder",
                    },
                    {
                      text: "Extruder Breakout Board",
                      link: "/printers/wanhao/duplicator6/major_components/extruder_board",
                    },
                    {
                      text: "Extruder Temperature Sensor",
                      link: "/printers/wanhao/duplicator6/major_components/extruder_temperature_sensor",
                    },
                    {
                      text: "FIRE HAZARD!",
                      link: "/printers/wanhao/duplicator6/major_components/fire_hazard",
                    },
                    {
                      text: "Motherboard Overview",
                      link: "/printers/wanhao/duplicator6/major_components/motherboard",
                    },
                    {
                      text: "Stepper Motors",
                      link: "/printers/wanhao/duplicator6/major_components/stepper_motors",
                    },
                  ],
                },
                {
                  text: "Useful Resources",
                  collapsed: true,
                  link: "/printers/wanhao/duplicator6/useful_references",
                  items: [
                    {
                      text: "Thermal Conductivity",
                      link: "/printers/wanhao/duplicator6/useful_references/thermal_conductivity",
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          text: "Xvico",
          collapsed: true,
          items: [
            {
              text: "X3",
              collapsed: true,
              items: [
                {
                  text: "XVICO X3 Pro",
                  link: "/printers/xvico/x3/pro",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  "/parts/": [
    {
      text: "Parts",
      link: "/parts/",
      items: [
        {
          text: "Beds",
          collapsed: true,
          items: [
            {
              text: "Printing on Glass",
              link: "/parts/beds/glass",
            },
            {
              text: "The heated bed, hotbed , buildplate",
              link: "/parts/beds/heatedpcb",
            },
          ],
        },
        {
          text: "Hotends",
          collapsed: true,
          items: [
            {
              text: "E3D V6",
              link: "/parts/hotends/e3dv6",
            },
          ],
        },
      ],
    },
  ],
  "/firmware/": [
    {
      text: "Firmware",
      link: "/firmware/",
      items: [
        {
          text: "Printer Calibration",
          link: "/firmware/calibration",
        },
        {
          text: "Klipper",
          collapsed: true,
          link: "/firmware/klipper",
          items: [
            {
              text: "HowTo Run BLTouch connected to RPi microcontroller",
              link: "/firmware/klipper/bltouch-with-raspberry-pi",
            },
          ],
        },
      ],
    },
  ],
  "/electronics/": [
    {
      text: "Electronics",
      link: "/electronics/",
      items: [
        {
          text: "Howto Connect your Hotbed (and or extruder) to a Mosfet",
          link: "/electronics/heatbed_mosfet",
        },
        {
          text: "RAMPS",
          link: "/electronics/ramps",
        },
      ],
    },
  ],
}
